[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
chit_fund_platform = "CrAEEmFufm1sTY3KHAmnKkj1yq2JPZux5PhrxquDc4cZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
